# Generated by Django 2.1.1 on 2018-10-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_auto_20181011_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='talker',
            field=models.CharField(max_length=50),
        ),
    ]
